### ISSUE TITLE
Input characters are missing

### ISSUE THREAD

**Issue by huanmeng-qwq** [Minecrell/TerminalConsoleAppender#27]
Output the message while inputting the string, and the input characters will be lost
\> xxxx
inputing the string and run(my log output is very fast)
```java
log.info("a msg");
```
string will be lost.

**Comment by huanmeng-qwq** [comment]
In IntelliJ IDEA

**Comment by SNWCreations** [comment]
I remember that the JLine may not work in IntelliJ IDEA terminal. It will print a message like "The advanced terminal features are not available in this environment".
And this library will use System.in stream instead of JLine when it can't detect terminal instance. The source code told me that.
So I think it is just a unsupported situation.
