### ISSUE TITLE
SimpleTerminalConsole will exit immediately if a terminal is not available.

### ISSUE THREAD

**Issue by ryantheleach** [Minecrell/TerminalConsoleAppender#6]
I'm not sure if this is a bug, or an intended feature, but applications that use SimpleTerminalConsole will exit immediately if a pseudo TTY is not present.

I understand that taking input from std.in then quitting is useful in situations where you wish to consume all the available input, like running and interpreting a prebuilt script.

However, this results in Applications that use TCA's SimpleTerminalConsole to quit immediately when run as a sub-process that doesn't inherit a terminal (Such as Velocity).

Examples are:

Docker when unintentionally not wrapped in a pseudo tty using the `-t` flag
Gradle Application Run configurations.

If this behavior isn't treated as a bug, what workaround do you suggest to applications?

If not a workaround, can a feature be added to STC to act in a daemon mode, where it won't quit until it receives a signal? Or is that the responsibility of Applications using your library? And if so, what would you recommend?

**Comment by stephan-gh** [comment]
When the standard input stream is closed, there will not ever be new input that can be consumed. Therefore it is only logical that `SimpleTerminalConsole` returns.

However, after `SimpleTerminalConsole` returns, it's up to the application to exit or continue running.
The behavior you are describing appears to be specific to Velocity - Paper, Waterfall and SpongeVanilla (and quite likely Forge) stay alive when run from a Gradle build script.

My guess would be that Velocity starts all new threads as daemons, and therefore exits after the main thread returns from the console routine. Functionality to keep it alive, if intended, should be added there. Usually this would be implemented by either:

  - Starting the thread that should keep running without daemon mode, so that the JVM does not exit after the console thread returns
  - Joining the thread or thread pool that should keep running from the console thread

**Comment by astei** [comment]
This should be fixed by VelocityPowered/Velocity@df7eb4ade.
